name: Run Tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest # Uses a Ubuntu environment.
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          python run_tests.py
